### ISSUE TITLE
tests fail unless time zone set to Berlin

### ISSUE THREAD

**Issue by ebowman** [zalando/java-sproc-wrapper#11]
This is failing on travis. I can reproduce locally by setting my machine's timezone to GMT.

    Failed tests:   parseAble(de.zalando.typemapper.core.fieldMapper.DateFieldMapperTest): parseAble("[Ljava.lang.String;@95fedf6" <from DATES_RESULTS[0]>, "class java.sql.Date" <from CLASSES[0]>)
      testHashCode(de.zalando.typemapper.postgres.PgArrayTest): expected:<24497024> but was:<1552105791>
      testEquals(de.zalando.typemapper.postgres.PgArrayTest): expected: de.zalando.typemapper.postgres.PgArray<{1,2,3}> but was: de.zalando.typemapper.postgres.PgArray<{1,2,3}>
      serializationTest[0](de.zalando.typemapper.postgres.PgSerializerTest): 
      serializationTest[1](de.zalando.typemapper.postgres.PgSerializerTest):

**Comment by hjacobs** [comment]
Fixed, thanks! https://travis-ci.org/zalando/java-sproc-wrapper
